INSERT INTO category (catelog, sort_order, parent_id, is_private)
SELECT 'Headphones', 4, 0, 0
WHERE NOT EXISTS (SELECT 1 FROM category WHERE catelog='Headphones' AND parent_id=0);

INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'WF10A Dual-Mode Gaming Headset','https://www.bestchoice.xin/#contact','/images/headphones/wf10a-gaming-headset.jpg','Bluetooth 6.0, 2.4G wireless and 3.5 mm wired connectivity. ≥10 m wireless range, ≤30 ms low latency, approximately 4-hour charging time and 1000 mAh battery. 50 mm driver, 20 Hz-20 kHz response, 32 Ω impedance and detachable boom microphone. MOQ: 100 units.',id,'Headphones','gaming',401,0 FROM category WHERE catelog='Headphones' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='WF10A Dual-Mode Gaming Headset' AND catelog_name='Headphones');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'WF18 Dual-Mode Gaming Headset','https://www.bestchoice.xin/#contact','/images/headphones/wf18-gaming-headset.jpg','Bluetooth 6.0, 2.4G wireless and 3.5 mm wired connectivity. ≥10 m wireless range, ≤30 ms low latency, approximately 4-hour charging time and 1000 mAh battery. 50 mm driver, 20 Hz-20 kHz response, 32 Ω impedance and boom microphone. MOQ: 100 units.',id,'Headphones','gaming',402,0 FROM category WHERE catelog='Headphones' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='WF18 Dual-Mode Gaming Headset' AND catelog_name='Headphones');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'F6B Dual-Mode Gaming Headset','https://www.bestchoice.xin/#contact','/images/headphones/f6b-gaming-headset.jpg','Bluetooth 6.0, 2.4G wireless and 3.5 mm wired connectivity. ≥10 m wireless range, ≤30 ms low latency, approximately 4-hour charging time and 1000 mAh battery. 50 mm driver, 20 Hz-20 kHz response, 32 Ω impedance and boom microphone. MOQ: 100 units.',id,'Headphones','gaming',403,0 FROM category WHERE catelog='Headphones' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='F6B Dual-Mode Gaming Headset' AND catelog_name='Headphones');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'F3A Dual-Mode Gaming Headset','https://www.bestchoice.xin/#contact','/images/headphones/f3a-gaming-headset.jpg','Bluetooth 6.0, 2.4G wireless and 3.5 mm wired connectivity. ≥10 m wireless range, ≤30 ms low latency, approximately 4-hour charging time and 800 mAh battery. 50 mm driver, 20 Hz-20 kHz response, 32 Ω impedance and boom microphone. MOQ: 100 units.',id,'Headphones','gaming',404,0 FROM category WHERE catelog='Headphones' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='F3A Dual-Mode Gaming Headset' AND catelog_name='Headphones');
