INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT '60D High-Contour Memory Foam Pillow','https://www.bestchoice.xin/#contact','/images/pillows/high-contour-pillow.jpg','62 × 35 × 10/7 cm · Approx. 940 g · Hydrophilic memory foam · Cool-feel or jersey cover · Reference price: CNY 66.3. MOQ: 100 pcs.',id,'Pillows','contour',301,0 FROM category WHERE catelog='Pillows' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='60D High-Contour Memory Foam Pillow' AND catelog_name='Pillows');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT '60D Medium-Contour Memory Foam Pillow','https://www.bestchoice.xin/#contact','/images/pillows/medium-contour-pillow.jpg','62 × 35 × 8/6 cm · Approx. 840 g · Hydrophilic memory foam · Cool-feel or jersey cover · Reference price: CNY 64.5. MOQ: 100 pcs.',id,'Pillows','contour',302,0 FROM category WHERE catelog='Pillows' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='60D Medium-Contour Memory Foam Pillow' AND catelog_name='Pillows');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT '60D Low-Contour Memory Foam Pillow','https://www.bestchoice.xin/#contact','/images/pillows/low-contour-pillow.jpg','62 × 35 × 6/4 cm · Approx. 585 g · Hydrophilic memory foam · Cool-feel or jersey cover · Reference price: CNY 55.7. MOQ: 100 pcs.',id,'Pillows','contour',303,0 FROM category WHERE catelog='Pillows' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='60D Low-Contour Memory Foam Pillow' AND catelog_name='Pillows');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT '60D Good Sleep Memory Foam Pillow','https://www.bestchoice.xin/#contact','/images/pillows/good-sleep-pillow.jpg','62 × 35 × 11/7 cm · Approx. 840 g · Hydrophilic memory foam · Cool-feel or jersey cover · Reference price: CNY 63.5. MOQ: 100 pcs.',id,'Pillows','ergonomic',304,0 FROM category WHERE catelog='Pillows' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='60D Good Sleep Memory Foam Pillow' AND catelog_name='Pillows');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT '60D Duckbill Adjustable Memory Foam Pillow','https://www.bestchoice.xin/#contact','/images/pillows/duckbill-adjustable-pillow.jpg','61 × 34 × 10/5 cm · Approx. 965 g · Hydrophilic memory foam · Cool-feel or jersey cover · Reference price: CNY 68.5. MOQ: 100 pcs.',id,'Pillows','adjustable',305,0 FROM category WHERE catelog='Pillows' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='60D Duckbill Adjustable Memory Foam Pillow' AND catelog_name='Pillows');
