-- Product data summarized from the Yongxuan Group 2025 catalogue, pages 19–28.
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Cast Film Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/cast-film-masterbatch.jpg','High-temperature-resistant filler masterbatch with stable flow and uniform dispersion for cast film production. Typical addition ratio: 10%–50%.',id,'Plastic Granules','film',201,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Cast Film Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Membrane Coating Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/membrane-coating-masterbatch.jpg','Uniformly dispersed coating filler designed for stable processing at high temperatures and a practical 10%–50% addition range.',id,'Plastic Granules','film',202,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Membrane Coating Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Blown Film Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/blown-film-masterbatch.jpg','Customizable filler for PO, PE and PP blown-film bags, developed for good gloss, dispersion and processing stability. Typical addition ratio: 10%–80%.',id,'Plastic Granules','film',203,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Blown Film Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'PP Hollow Board Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/pp-hollow-board-masterbatch.jpg','Stable, well-dispersed filler masterbatch for PP hollow board, helping improve hardness and surface gloss. Typical addition ratio: 20%–70%.',id,'Plastic Granules','extrusion',204,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='PP Hollow Board Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Plastic Sheet Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/plastic-sheet-masterbatch.jpg','Micronized calcium-carbonate masterbatch for plastic sheet and thermoformed products, supporting rigidity, toughness and production efficiency.',id,'Plastic Granules','extrusion',205,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Plastic Sheet Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Plastic Pipe Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/plastic-pipe-masterbatch.jpg','High-temperature-resistant, free-flowing filler for plastic pipe and related extrusion applications, with uniform dispersion and stable output.',id,'Plastic Granules','extrusion',206,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Plastic Pipe Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Blow Molding Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/blow-molding-masterbatch.jpg','Filler masterbatch for cosmetic, pharmaceutical and detergent bottles, designed for gloss, toughness, hardness and clean dispersion.',id,'Plastic Granules','molding',207,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Blow Molding Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Injection Molding Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/injection-molding-masterbatch.jpg','Stable filler for injection-molded electronics parts, trays, toys and general plastic products. Supports uniform dispersion and production yield.',id,'Plastic Granules','molding',208,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Injection Molding Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Wire Drawing Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/wire-drawing-masterbatch.jpg','Modified functional filler for spunbond nonwoven and plastic wire-drawing processes, developed for compatibility, smoother spinning and lower raw-material cost.',id,'Plastic Granules','extrusion',209,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Wire Drawing Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Flame Retardant Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/flame-retardant-masterbatch.jpg','Functional masterbatch formulated to improve flame resistance in plastic compounds through heat absorption, surface coverage and radical inhibition mechanisms.',id,'Plastic Granules','functional',210,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Flame Retardant Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Natural Anhydrous Calcium Sulfate Functional Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/anhydrous-calcium-sulfate-masterbatch.jpg','Functional masterbatch based on natural anhydrous calcium sulfate to improve processing flow, mechanical performance and product quality in food-packaging and hygiene applications.',id,'Plastic Granules','functional',211,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Natural Anhydrous Calcium Sulfate Functional Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Biodegradable PBAT Blown Film Material','https://www.bestchoice.xin/#contact','/images/plastic-granules/biodegradable-pbat-blown-film.jpg','PBAT-based blown-film material with flexibility, transparency and thermal stability, designed for products that can biodegrade under suitable natural conditions.',id,'Plastic Granules','sustainable',212,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Biodegradable PBAT Blown Film Material' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Breathable Functional Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/breathable-functional-masterbatch.jpg','Polyolefin-based functional masterbatch that forms micropores after processing, providing breathability for packaging, medical and hygiene products.',id,'Plastic Granules','functional',213,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Breathable Functional Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Photooxidative Degradation Masterbatch','https://www.bestchoice.xin/#contact','/images/plastic-granules/photooxidative-degradation-masterbatch.jpg','Photooxidative additive masterbatch designed to promote polymer degradation under light and oxygen exposure for selected disposable plastic applications.',id,'Plastic Granules','sustainable',214,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Photooxidative Degradation Masterbatch' AND catelog_name='Plastic Granules');
INSERT INTO sites (name, url, logo, desc, catelog_id, catelog_name, product_type, sort_order, is_private)
SELECT 'Calcium Carbonate Powder','https://www.bestchoice.xin/#contact','/images/plastic-granules/calcium-carbonate-powder.jpg','Heavy calcium carbonate powder in multiple mesh grades for papermaking, plastics, rubber coatings and building materials, offering high whiteness and good dispersibility.',id,'Plastic Granules','mineral',215,0 FROM category WHERE catelog='Plastic Granules' AND NOT EXISTS (SELECT 1 FROM sites WHERE name='Calcium Carbonate Powder' AND catelog_name='Plastic Granules');
